### ISSUE TITLE
Complete Javascript tutorials from w3 schools

### ISSUE THREAD

**Issue by yakshit1515** [yakshit1515/React-Mesons#4]
@avkour13 please pick JavaScript from w3schools and try to complete it by Friday.

https://www.w3schools.com/js/default.asp

Please upload your latest code file here by EOD with a screenshot of the UI.

**Comment by avkour13** [comment]
<img width="960" alt="2022-05-11 (1)" src="https://user-images.githubusercontent.com/72076045/167940835-fbbfd70c-5f68-4511-b835-0cd8e802f76f.png">
<img width="960" alt="2022-05-11" src="https://user-images.githubusercontent.com/72076045/167940837-eb7ecc07-6b79-46b8-b4f9-583fe0372472.png">
